/**
 * Custom Resource Lambda: Create/delete admin users in Cognito User Pool.
 * Temporary passwords are auto-generated by Cognito and delivered via invitation email.
 */
import {
  CognitoIdentityProviderClient,
  AdminCreateUserCommand,
  AdminDeleteUserCommand,
  DeliveryMediumType,
} from '@aws-sdk/client-cognito-identity-provider';

const client = new CognitoIdentityProviderClient({});

interface CloudFormationEvent {
  RequestType: 'Create' | 'Update' | 'Delete';
  ResourceProperties: { UserPoolId: string; Emails: string };
  OldResourceProperties?: { UserPoolId: string; Emails: string };
}

function parseEmails(raw: string): string[] {
  const parsed: string[] = JSON.parse(raw);
  return [...new Set(parsed)].sort();
}

async function createUser(userPoolId: string, email: string): Promise<void> {
  try {
    await client.send(new AdminCreateUserCommand({
      UserPoolId: userPoolId,
      Username: email,
      UserAttributes: [
        { Name: 'email', Value: email },
        { Name: 'email_verified', Value: 'true' },
      ],
      DesiredDeliveryMediums: [DeliveryMediumType.EMAIL],
    }));
  } catch (e: any) {
    if (e.name === 'UsernameExistsException') {
      console.log('User already exists, skipping');
      return;
    }
    throw e;
  }
}

async function deleteUser(userPoolId: string, email: string): Promise<void> {
  try {
    await client.send(new AdminDeleteUserCommand({
      UserPoolId: userPoolId,
      Username: email,
    }));
  } catch (e: any) {
    if (e.name === 'UserNotFoundException') {
      console.log('User not found, skipping delete');
      return;
    }
    throw e;
  }
}

export const handler = async (event: CloudFormationEvent) => {
  const { UserPoolId, Emails } = event.ResourceProperties;
  const emails = parseEmails(Emails);
  const physicalResourceId = 'repo-patrol-admin-users';

  console.log(`RequestType: ${event.RequestType}, user count: ${emails.length}`);

  if (event.RequestType === 'Create') {
    for (const email of emails) {
      await createUser(UserPoolId, email);
    }
    return { PhysicalResourceId: physicalResourceId };
  }

  if (event.RequestType === 'Update') {
    const oldEmails = event.OldResourceProperties
      ? parseEmails(event.OldResourceProperties.Emails)
      : [];

    const toAdd = emails.filter((e) => !oldEmails.includes(e));
    const toRemove = oldEmails.filter((e) => !emails.includes(e));

    console.log(`Adding ${toAdd.length} users, removing ${toRemove.length} users`);

    for (const email of toAdd) {
      await createUser(UserPoolId, email);
    }
    for (const email of toRemove) {
      await deleteUser(UserPoolId, email);
    }
    return { PhysicalResourceId: physicalResourceId };
  }

  // Delete
  for (const email of emails) {
    await deleteUser(UserPoolId, email);
  }
  return { PhysicalResourceId: physicalResourceId };
};
